// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./Hero2")),
  hero_3: dynamic(() => import("./Hero3")),
  image_and_text: dynamic(() => import("./ImageAndText")),
  testing_slice: dynamic(() => import("./TestingSlice")),
  text_block_test: dynamic(() => import("./TextBlockTest")),
};
